"""E.R.I.I. — Experiential Recall & Impression Integration Engine

Export public API symbols.
Follows Google Python Style Guide.
"""

from erii.adapters.base import BaseLLMAdapter
from erii.adapters.custom_adapter import CallableLLMAdapter
from erii.adapters.openai_adapter import OpenAIAdapter
from erii.adapters.persona_compiler import (
    BasePersonaCompilerAdapter,
    CallablePersonaCompilerAdapter,
    LLMPersonaCompilerAdapter,
)
from erii.core.persona_compilation import PersonaCompiler
from erii.core.persona_context import PersonaManifestRequiredError
from erii.core.recall import RecallBudgetUnsatisfiedError
from erii.core.temporal_history import TemporalHistoryConflictError
from erii.core.queue.base import BaseTaskQueue
from erii.core.queue.persistent_queue import PersistentTaskQueue
from erii.engine import ERIIEngine
from erii.models.config import ERIIConfig
from erii.models.adjudication import (
    AdjudicationBatchResult,
    AdjudicationRecord,
    CandidateConflictError,
    DecisionOutcome,
    DecisionReceipt,
    EvidenceCitation,
    EvidenceReference,
    GrowthTriggerKind,
    OpenLoopResolutionCandidate,
    OpenLoopSpecCandidate,
    PersonaGrowthConflictError,
    PersonaGrowthDecision,
    PersonaGrowthIntentCandidate,
    PersonaGrowthProposal,
    PersonaGrowthStatus,
    PromiseConditionCandidate,
    PromiseConditionConfirmationCandidate,
    PromiseResolutionCandidate,
    PromiseSpecCandidate,
    RelationshipCandidateBatch,
    RelationshipEventCandidate,
    RelationshipPolicySpec,
    RelationshipSignal,
    RelationshipSignalType,
    SignalStrength,
    SourceMessage,
    SourceProcessingMode,
    SourceRole,
    SourceTurn,
    TemporalPayloadCandidate,
    WorldMomentCandidate,
)
from erii.models.node import MemoryNode, MemoryState, MemoryType, MemoryVisibility
from erii.models.pack import MemoryPack
from erii.models.persona import (
    CanonicalPremiseTemplateCandidate,
    FormativeExperienceCandidate,
    FormativeLinkCandidate,
    FormativeLinkType,
    MeaningCapsuleCandidate,
    PersonaActivationTier,
    PersonaApplicability,
    PersonaClaimCandidate,
    PersonaClaimKind,
    PersonaCompilationConflictError,
    PersonaCompilationDecision,
    PersonaCompilationProposal,
    PersonaCompilationStatus,
    PersonaInterpretationBasis,
    PersonaManifest,
    PersonaManifestCandidate,
    PersonaScope,
    PersonaSourceSpan,
)
from erii.models.recall import (
    BudgetOmission,
    BudgetReport,
    EventRecallProjection,
    MemoryRecallProjection,
    PersonaDelivery,
    PersonaRecallContext,
    PersonaRecallProjection,
    RecallAudience,
    RecallBudget,
    RecallNotice,
    RecallNoticeSeverity,
    RecallOptions,
    RecallRequest,
    RecallResult,
    RecallSignalAuthority,
    RecallSignalReason,
    RecallSignalType,
    RecallSignalProjection,
    RecallSourceReference,
    RecallTemporalContext,
    ReinforcementReport,
    RelationshipMetric,
    RelationshipNarrativeProjection,
    RelationshipRecallContext,
    RelationshipRecallStatus,
    WorldTime,
)
from erii.models.relationship import (
    BaselineLevel,
    BeliefOperation,
    BeliefUpdate,
    CharacterBlueprint,
    CurrentBelief,
    EventConflictError,
    IdentityKind,
    PersonaConflictError,
    PremiseExperience,
    PremisePolicy,
    RelationshipBaseline,
    RelationshipEvent,
    RelationshipEventType,
    RelationshipNotFoundError,
    RelationshipProfile,
    RelationshipPremise,
    RelationshipPremiseMode,
    RelationshipSnapshot,
    RelationshipState,
    StateReason,
    TemporalContext,
)
from erii.models.temporal import (
    OpenLoopResolution,
    OpenLoopResolutionKind,
    OpenLoopSpec,
    PromiseCondition,
    PromiseConditionConfirmation,
    PromiseResolution,
    PromiseResolutionKind,
    PromiseResponsibleParty,
    PromiseSpec,
    TemporalPayload,
    TemporalPayloadType,
    WorldMoment,
    temporal_payload_from_dict,
    temporal_payload_to_dict,
)
from erii.models.turn import (
    ContinuityAssessmentStatus,
    ContinuityVerdict,
    ContextSignalSource,
    DeliveryDisposition,
    InteractionContextSignal,
    ReplyAttemptConflictError,
    ReplyAttemptRecord,
    ReplyAttemptStage,
    ReplyContinuityAssessment,
    SourceTranscript,
    SourceProcessingChannel,
    SourceProcessingOutcome,
    SourceProcessingPlan,
    SourceProcessingState,
    SourceTurnReceipt,
    TurnConflictError,
    TurnMessage,
    TurnNotFoundError,
    TurnRecord,
    TurnRole,
    TurnStatus,
    TurnTerminalConflictError,
)
from erii.security.sanitizer import SecuritySanitizer
from erii.renderers import (
    MarkdownRecallRenderer,
    RecallAudienceMismatchError,
    RecallRenderBudgetError,
    RecallRenderError,
    RecallRenderer,
)
from erii.storage.base import BaseStorage
from erii.storage.file_storage import FileStorage
from erii.storage.sqlite_storage import SQLiteStorage
from erii.vector.base import BaseEmbeddingProvider, BaseVectorStore
from erii.vector.in_memory_vector import (
    CallableEmbeddingAdapter,
    DummyEmbeddingProvider,
    InMemoryVectorStore,
)
from erii._version import __version__

__all__ = [
    "__version__",
    "BasePersonaCompilerAdapter",
    "BaselineLevel",
    "BudgetOmission",
    "BudgetReport",
    "CallablePersonaCompilerAdapter",
    "CanonicalPremiseTemplateCandidate",
    "EventRecallProjection",
    "FormativeExperienceCandidate",
    "FormativeLinkCandidate",
    "FormativeLinkType",
    "LLMPersonaCompilerAdapter",
    "MarkdownRecallRenderer",
    "MeaningCapsuleCandidate",
    "MemoryRecallProjection",
    "OpenLoopResolution",
    "OpenLoopResolutionCandidate",
    "OpenLoopResolutionKind",
    "OpenLoopSpec",
    "OpenLoopSpecCandidate",
    "PersonaActivationTier",
    "PersonaApplicability",
    "PersonaClaimCandidate",
    "PersonaClaimKind",
    "PersonaCompilationConflictError",
    "PersonaCompilationDecision",
    "PersonaCompilationProposal",
    "PersonaCompilationStatus",
    "PersonaCompiler",
    "PersonaDelivery",
    "PersonaInterpretationBasis",
    "PersonaManifest",
    "PersonaManifestCandidate",
    "PersonaManifestRequiredError",
    "PersonaRecallContext",
    "PersonaRecallProjection",
    "PersonaScope",
    "PersonaSourceSpan",
    "PremiseExperience",
    "PremisePolicy",
    "PromiseCondition",
    "PromiseConditionCandidate",
    "PromiseConditionConfirmation",
    "PromiseConditionConfirmationCandidate",
    "PromiseResolution",
    "PromiseResolutionCandidate",
    "PromiseResolutionKind",
    "PromiseResponsibleParty",
    "PromiseSpec",
    "PromiseSpecCandidate",
    "RecallAudience",
    "RecallAudienceMismatchError",
    "RecallBudget",
    "RecallBudgetUnsatisfiedError",
    "RecallNotice",
    "RecallNoticeSeverity",
    "RecallOptions",
    "RecallRenderBudgetError",
    "RecallRenderError",
    "RecallRenderer",
    "RecallRequest",
    "RecallResult",
    "RecallSignalAuthority",
    "RecallSignalReason",
    "RecallSignalType",
    "RecallSignalProjection",
    "RecallSourceReference",
    "RecallTemporalContext",
    "ReinforcementReport",
    "RelationshipBaseline",
    "RelationshipMetric",
    "RelationshipNarrativeProjection",
    "RelationshipPremise",
    "RelationshipPremiseMode",
    "RelationshipRecallContext",
    "RelationshipRecallStatus",
    "WorldTime",
    "AdjudicationBatchResult",
    "AdjudicationRecord",
    "ERIIEngine",
    "ERIIConfig",
    "MemoryNode",
    "MemoryType",
    "MemoryState",
    "MemoryVisibility",
    "MemoryPack",
    "BeliefOperation",
    "BeliefUpdate",
    "CharacterBlueprint",
    "CandidateConflictError",
    "CurrentBelief",
    "DecisionOutcome",
    "DecisionReceipt",
    "EventConflictError",
    "EvidenceCitation",
    "EvidenceReference",
    "GrowthTriggerKind",
    "IdentityKind",
    "PersonaConflictError",
    "PersonaGrowthConflictError",
    "PersonaGrowthDecision",
    "PersonaGrowthIntentCandidate",
    "PersonaGrowthProposal",
    "PersonaGrowthStatus",
    "RelationshipCandidateBatch",
    "RelationshipEvent",
    "RelationshipEventCandidate",
    "RelationshipEventType",
    "RelationshipNotFoundError",
    "RelationshipProfile",
    "RelationshipPolicySpec",
    "RelationshipSignal",
    "RelationshipSignalType",
    "RelationshipSnapshot",
    "RelationshipState",
    "StateReason",
    "TemporalContext",
    "TemporalHistoryConflictError",
    "TemporalPayload",
    "TemporalPayloadCandidate",
    "TemporalPayloadType",
    "WorldMoment",
    "WorldMomentCandidate",
    "temporal_payload_from_dict",
    "temporal_payload_to_dict",
    "SignalStrength",
    "SourceMessage",
    "SourceProcessingMode",
    "SourceRole",
    "SourceTurn",
    "SourceTranscript",
    "ContinuityAssessmentStatus",
    "ContinuityVerdict",
    "ContextSignalSource",
    "DeliveryDisposition",
    "InteractionContextSignal",
    "ReplyAttemptConflictError",
    "ReplyAttemptRecord",
    "ReplyAttemptStage",
    "ReplyContinuityAssessment",
    "SourceProcessingChannel",
    "SourceProcessingOutcome",
    "SourceProcessingPlan",
    "SourceProcessingState",
    "SourceTurnReceipt",
    "TurnConflictError",
    "TurnMessage",
    "TurnNotFoundError",
    "TurnRecord",
    "TurnRole",
    "TurnStatus",
    "TurnTerminalConflictError",
    "BaseLLMAdapter",
    "CallableLLMAdapter",
    "OpenAIAdapter",
    "BaseStorage",
    "FileStorage",
    "SQLiteStorage",
    "SecuritySanitizer",
    "BaseTaskQueue",
    "PersistentTaskQueue",
    "BaseEmbeddingProvider",
    "BaseVectorStore",
    "CallableEmbeddingAdapter",
    "DummyEmbeddingProvider",
    "InMemoryVectorStore",
]
